#!/bin/bash
export ADMIN_MAIL=...
export IMAGER_S3_BUCKET=...
export IMAGER_S3_KEY=...
export IMAGER_S3_SECRET=...
export NODE_ENV=development
export NODE_PATH=./config:./app/controllers:./lib
#npm start
forever start server.js
